version: "3"
services:
  iam:
    image: go-iam
    build: ..
    container_name: iam-server
    ports:
      - "12345:12345"
    depends_on:
      - db
    networks:
      - iam_net
  db:
    image: mysql:latest
    restart: always
    container_name: iam-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=iam
    networks:
      - iam_net
networks:
  iam_net:
