server:
  mode: "debug"
  port: "12345"

mysql:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "123456"
  database: "iam"
  logFile: "./storage/db/db.log"

log:
  level: "debug"
  accessLog: "./storage/log/access.log"
  errorLog: "./storage/log/access.log"
  console: true

email:
  smtp_key: "tqzrnigzcbjiehbc"
  from_email: "yeebingchen@qq.com"

