server:
  mode: "debug"
  port: "12345"

mysql:
  host: "dbl"
  port: "3306"
  username: "root"
  password: "123456"
  database: "iam"
  logFile: "./storage/db/db.log"

email:
  smtpKey: "tqzrnigzcbjiehbc"
  fromEmail: "yeebingchen@qq.com"

log:
  level: "debug"
  accessLog: "./storage/log/access.log"
  errorLog: "./storage/log/error.log"
  console: true
